version: "3.9"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    # image: ghcr.io/OWNER/shoptalk-api:local
    env_file: .env
    environment:
      # Ensure the API can find the persistent Chroma DB inside the container
      DB_PATH: /vectordb
    volumes:
      - vectordb:/vectordb
      - hf_cache:/root/.cache/huggingface  # caches models across rebuilds
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 5s
      start_period: 20s

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    # image: ghcr.io/OWNER/shoptalk-ui:local
    env_file: .env
    environment:
      API_URL: http://api:8000
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "8501:8501"

volumes:
  vectordb:
  hf_cache:
